import { NextRequest } from "next/server";
import { supabaseAdmin } from "@/lib/supabase";
import { getContext } from "@/lib/ownership";
import { can, isStaff } from "@/lib/permissions";
import { logAudit } from "@/lib/audit";
import { encryptSecret } from "@/lib/crypto";
import { fetchConnectedAccount, subscribeToWebhooks } from "@/lib/instagram";

/**
 * Connect an Instagram account to a business by supplying its access token.
 *
 * Kept as a fallback for tokens generated by hand in the Meta dashboard. The
 * primary path is now Instagram Business Login (/api/auth/instagram), which a
 * Meta reviewer can actually complete.
 *
 * The token is the proof of ownership: `ig_account_id` is derived from Meta's
 * /me response, never from the request body. If callers could name their own
 * account id they could claim another business's Instagram account and start
 * receiving that business's webhooks.
 */
export async function POST(request: NextRequest) {
  const ctx = await getContext();
  if (!ctx) return Response.json({ error: "Unauthorized" }, { status: 401 });
  if (!can(ctx.user.role, "businesses")) return Response.json({ error: "Not found" }, { status: 404 });

  const body = await request.json();
  const businessId = String(body?.business_id ?? "");
  const token = String(body?.access_token ?? "").trim();
  if (!businessId || !token) {
    return Response.json({ error: "business_id and access_token are required" }, { status: 400 });
  }

  // 1. Does the caller own the target business?
  let bq = supabaseAdmin.from("businesses").select("id, client_id").eq("id", businessId);
  if (!isStaff(ctx.user.role)) bq = bq.eq("client_id", ctx.user.id);
  const { data: business } = await bq.maybeSingle<{ id: string; client_id: string }>();
  if (!business) return Response.json({ error: "Not found" }, { status: 404 });

  // 2. Plan limit — enforced server-side, per client, at connect time.
  //    Staff are exempt: the plan cap is a customer-billing construct, and the
  //    operator's team must be able to add more accounts at will.
  if (!isStaff(ctx.user.role)) {
    const { data: sub } = await supabaseAdmin
      .from("subscriptions")
      .select("plans(max_ig_accounts)")
      .eq("client_id", business.client_id)
      .maybeSingle<{ plans: { max_ig_accounts: number } | null }>();

    const maxAccounts = sub?.plans?.max_ig_accounts ?? 0;
    const { data: owned } = await supabaseAdmin
      .from("instagram_accounts")
      .select("id, businesses!inner(client_id)")
      .eq("businesses.client_id", business.client_id);

    if ((owned?.length ?? 0) >= maxAccounts) {
      return Response.json(
        {
          error: `Your plan allows ${maxAccounts} Instagram account${maxAccounts === 1 ? "" : "s"}. Upgrade to connect more.`,
        },
        { status: 402 }
      );
    }
  }

  // 3. Ask Meta who this token belongs to. This both validates the token and
  //    establishes the account identity — the caller does not get a say.
  let meta;
  try {
    meta = await fetchConnectedAccount(token);
  } catch (err) {
    return Response.json(
      { error: `Instagram rejected that token: ${(err as Error).message}` },
      { status: 400 }
    );
  }
  if (!meta.user_id) {
    return Response.json({ error: "Could not resolve an Instagram account from that token." }, { status: 400 });
  }

  // 4. Already connected? ig_account_id is globally unique — it is the webhook
  //    routing key, so two businesses cannot share one.
  const { data: taken } = await supabaseAdmin
    .from("instagram_accounts")
    .select("id")
    .eq("ig_account_id", meta.user_id)
    .maybeSingle();
  if (taken) {
    return Response.json({ error: "That Instagram account is already connected." }, { status: 409 });
  }

  const { data, error } = await supabaseAdmin
    .from("instagram_accounts")
    .insert({
      business_id: businessId,
      ig_account_id: meta.user_id, // <- from Meta, not the request
      username: meta.username,
      name: meta.name,
      profile_picture_url: meta.profile_picture_url,
      access_token: encryptSecret(token), // never stored plaintext
      status: isStaff(ctx.user.role) ? "approved" : "pending",
    })
    .select("id, ig_account_id, username, name, status") // never select access_token
    .single();

  if (error) return Response.json({ error: error.message }, { status: 500 });

  // Nothing subscribed newly-connected accounts before, so an account could look
  // healthy and silently never receive a DM. Idempotent. Non-fatal: the account is
  // connected regardless, so surface a warning rather than unwind a good connect.
  let warning: string | null = null;
  try {
    await subscribeToWebhooks(token);
  } catch (err) {
    warning = `Connected, but subscribing to messages failed: ${(err as Error).message}`;
  }

  await logAudit(ctx.user, {
    action: "account.connect",
    targetType: "instagram_account",
    targetId: data.id,
    targetLabel: data.username ?? data.ig_account_id,
  });

  return Response.json(warning ? { ...data, warning } : data, { status: 201 });
}
